name: Download All Maps

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight (optional, adjust as needed)
  push:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install JavaFX SDK
        run: |
          # Define JavaFX version and URL
          JAVA_FX_VERSION="20.0.1"
          JAVA_FX_URL="https://download2.gluonhq.com/openjfx/${JAVA_FX_VERSION}/javafx-sdk-${JAVA_FX_VERSION}_linux-x64_bin-sdk.zip"
          
          # Download and unzip JavaFX SDK
          wget $JAVA_FX_URL -O javafx-sdk.zip
          unzip javafx-sdk.zip -d $HOME/javafx
          echo "JAVA_FX_HOME=$HOME/javafx/javafx-sdk-${JAVA_FX_VERSION}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Download all maps
        run: ./gradlew downloadAll

      - name: Archive downloaded maps
        run: |
          mkdir -p archive
          zip -r archive/OCTMaps.zip OCTMaps
          mv build/libs/*.jar archive/

      - name: Upload downloaded maps and jar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: OCTMaps
          path: archive/
          retention-days: 7 # Keep the artifact for 7 days (optional, adjust as needed)
