name: Download All Maps

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight (optional, adjust as needed)
  push:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Download all maps
        run: |
           wget https://cdn.azul.com/zulu/bin/zulu17.52.17-ca-fx-jdk17.0.12-linux_x64.tar.gz
          tar -xzvf zulu17.52.17-ca-fx-jdk17.0.12-linux_x64.tar.gz
          export PATH=`pwd`/zulu17.52.17-ca-fx-jdk17.0.12-linux_x64/bin/:$PATH
          export JAVA_HOME=`pwd`/zulu17.52.17-ca-fx-jdk17.0.12-linux_x64/
          ./gradlew downloadAll

      - name: Archive downloaded maps
        run: |
          mkdir -p archive
          zip -r archive/OCTMaps.zip OCTMaps
          mv build/libs/*.jar archive/

      - name: Upload downloaded maps and jar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: OCTMaps
          path: archive/
          retention-days: 7 # Keep the artifact for 7 days (optional, adjust as needed)